formatter: markdown

header-from: main.tf

recursive:
  enabled: true
  path: modules

sections:
  show:
    - requirements
    - inputs
    - outputs
    - resources

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name